### ISSUE TITLE
Confirm and cancel switched over on Knulli (downloaded through portmaster)

### ISSUE THREAD

**Issue by SirPrimalform** [JanTrueno/Moonlight-Embedded-Launcher#1]
I've installed your lovely launcher through portmaster today on Knulli and found that B is acting as confirm and A as cancel (matching an Xbox layout but not matching the labels on my device). At first I assumed this to be a design choice you made, but I've noticed in the readme you mention that A should be confirm and B cancel. 

In the short-term, is there a way for me to swap them by editing a config file?

As a side note, would it be possible to add an option to the launcher that swaps between "match labels" and "match layout" for the ABXY when launching a game?

**Comment by JanTrueno** [comment]
Hi!
Thanks for using my launcher.  I did notice this issue while developing. Its actually a system wide "issue" on Knulli, but also on other systems like the stock OS from the Trimui Smart Pro. The same behaviour is seen on other ports. However on all the other cfw's they're correctly mapped. I suppose I could add a switch but since its just a launcher, I didn't think it was worth the effort. Sorry that I dont have an easy solution for you right now, but if I ever revisit this launcher I will definitely implement this feature. Some harder solutions would be to open up the main.lua from the launcher and start swapping the input code. The other would be to edit the gamecontrollerdb file from knulli, which I definitely do not recommend.

**Comment by SirPrimalform** [comment]
Hi, thanks for the suggestions. I'm no programmer but it looks like lua is very readable and you've commented the code lots. 

Ok, I started writing this comment thinking I'd post it and come back later after trying the fix, but it ended up being so easy that I've already done it. Thanks for your help!

Well you can consider this issue closed (at least for me). I guess if the A and B mapping was tied to a constant at the beginning of main.lua it could make that edit simpler for future users. I hope you do add some other features one day, but it's already much appreciated. Thanks!
